version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building...
      - echo Build success!
      - echo Testing...
      - echo Test success!

reports:
  report-group-name:
    files:
      - '**/*'
